### ISSUE TITLE
레퍼런스

### ISSUE THREAD

**Issue by jtrimind** [jtrimind/crispy-eureka#1]
https://www.e-gen.or.kr/egen/search_pharmacy.do

**Comment by acuranetics** [comment]
https://masksaja.com/

**Comment by jtrimind** [comment]
아이콘: https://material-ui.com/components/material-icons/

**Comment by acuranetics** [comment]
알약 아이콘 : https://www.pinclipart.com/maxpin/hboTRo/

**Comment by acuranetics** [comment]
인포메이션 아이콘 : https://www.flaticon.com/kr/free-icon/information-button_1176
