### ISSUE TITLE
서비스 이름

### ISSUE THREAD

**Issue by acuranetics** [jtrimind/crispy-eureka#6]
1. 지금(여는)약국 : 지금 열려있는 약국을 확인 할 수 있다는 네이밍

2. 바로약국 : 바로 찾아갈 수 있는 약국을 보여준다는 네이밍

**Comment by acuranetics** [comment]
3. 당장약국 : 당근마켓을 wish한 네이밍...

**Comment by jtrimind** [comment]
당장약국으로 설정.
favicon도 바꾸면 좋겠네요

**Comment by acuranetics** [comment]
[favicon.zip](https://github.com/jtrimind/crispy-eureka/files/5611690/favicon.zip)
파비콘
